/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import javax.swing.JLabel;
import projek_latih2.login;

/**
 *
 * @author Adrian Aditya P
 */
public class bottomMenu extends javax.swing.JPanel {

    /**
     * Creates new form bottomMenu
     */
    public bottomMenu() {
        initComponents();
    }
    public JLabel getlb_Title(){
        return lb_Title;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slider1 = new Method.Slider();
        lb_Title = new javax.swing.JLabel();
        lb_timeStart = new javax.swing.JLabel();
        lb_TimeEnd = new javax.swing.JLabel();
        lb_play = new javax.swing.JLabel();
        lb_pause = new javax.swing.JLabel();
        lb_previous = new javax.swing.JLabel();
        lb_next = new javax.swing.JLabel();
        lb_stop = new javax.swing.JLabel();
        lb_mix = new javax.swing.JLabel();
        lb_Nomix = new javax.swing.JLabel();
        lb_repeat = new javax.swing.JLabel();
        lb_repeatOne = new javax.swing.JLabel();
        lb_NoRepeat = new javax.swing.JLabel();

        setBackground(new java.awt.Color(19, 19, 44));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(slider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 360, -1));

        lb_Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lb_Title.setForeground(new java.awt.Color(255, 255, 255));
        lb_Title.setText("Song Title");
        add(lb_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lb_timeStart.setForeground(new java.awt.Color(255, 255, 255));
        lb_timeStart.setText("00.00");
        add(lb_timeStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        lb_TimeEnd.setForeground(new java.awt.Color(255, 255, 255));
        lb_TimeEnd.setText("03:00");
        add(lb_TimeEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        lb_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/play.png"))); // NOI18N
        add(lb_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 40, 30));

        lb_pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pause.png"))); // NOI18N
        add(lb_pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 50, 30));

        lb_previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/previous.png"))); // NOI18N
        add(lb_previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 40, 30));

        lb_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/next.png"))); // NOI18N
        add(lb_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 40, 30));

        lb_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/stop.png"))); // NOI18N
        add(lb_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 40, 30));

        lb_mix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mix.png"))); // NOI18N
        add(lb_mix, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 50, 40));

        lb_Nomix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/no mix.png"))); // NOI18N
        add(lb_Nomix, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 60, 40));

        lb_repeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/repeat.png"))); // NOI18N
        add(lb_repeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        lb_repeatOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/repeat one.png"))); // NOI18N
        add(lb_repeatOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 40, 30));

        lb_NoRepeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/no repeat.png"))); // NOI18N
        add(lb_NoRepeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 50, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_NoRepeat;
    private javax.swing.JLabel lb_Nomix;
    private javax.swing.JLabel lb_TimeEnd;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JLabel lb_mix;
    private javax.swing.JLabel lb_next;
    private javax.swing.JLabel lb_pause;
    private javax.swing.JLabel lb_play;
    private javax.swing.JLabel lb_previous;
    private javax.swing.JLabel lb_repeat;
    private javax.swing.JLabel lb_repeatOne;
    private javax.swing.JLabel lb_stop;
    private javax.swing.JLabel lb_timeStart;
    private Method.Slider slider1;
    // End of variables declaration//GEN-END:variables
}
