
package projek_latih2;
import Menu_utama.Playlist;
import Menu_utama.Search;
import Menu_utama.Home;
import Menu_utama.Artist;
import java.awt.Color;
import Method.ScrollBar;
import java.awt.Color;
/**
 *
 * @author Adrian Aditya P
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        init();
        //setBackground(new Color(0,0,0,0));
    }
    private void init(){
        ps_utama.setVerticalScrollBar(new ScrollBar());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_atas = new javax.swing.JPanel();
        pn_kiri = new javax.swing.JPanel();
        ikon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pn_Home = new javax.swing.JPanel();
        L_Home = new javax.swing.JLabel();
        pn_Search = new javax.swing.JPanel();
        L_Search = new javax.swing.JLabel();
        pn_Artist = new javax.swing.JPanel();
        L_Artist = new javax.swing.JLabel();
        pn_Playlist = new javax.swing.JPanel();
        L_Playlist = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        ps_utama = new javax.swing.JScrollPane();
        pn_utama = new javax.swing.JPanel();
        pn_bawah = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_atas.setBackground(new java.awt.Color(19, 19, 44));
        pn_atas.setPreferredSize(new java.awt.Dimension(1260, 600));
        pn_atas.setLayout(new java.awt.BorderLayout());

        pn_kiri.setBackground(new java.awt.Color(4, 1, 32));
        pn_kiri.setPreferredSize(new java.awt.Dimension(150, 521));

        ikon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adrian Aditya P\\Downloads\\Group 30.png")); // NOI18N
        ikon.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Musikku");

        L_Home.setText("> Home");
        L_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L_HomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_HomeLayout = new javax.swing.GroupLayout(pn_Home);
        pn_Home.setLayout(pn_HomeLayout);
        pn_HomeLayout.setHorizontalGroup(
            pn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_HomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pn_HomeLayout.setVerticalGroup(
            pn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Home)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_Search.setText("> Search");
        L_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L_SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L_SearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_SearchLayout = new javax.swing.GroupLayout(pn_Search);
        pn_Search.setLayout(pn_SearchLayout);
        pn_SearchLayout.setHorizontalGroup(
            pn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_SearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pn_SearchLayout.setVerticalGroup(
            pn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_Artist.setText("> Artist");
        L_Artist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_ArtistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L_ArtistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L_ArtistMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_ArtistLayout = new javax.swing.GroupLayout(pn_Artist);
        pn_Artist.setLayout(pn_ArtistLayout);
        pn_ArtistLayout.setHorizontalGroup(
            pn_ArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ArtistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_Artist, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pn_ArtistLayout.setVerticalGroup(
            pn_ArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ArtistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Artist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        L_Playlist.setText("> Playlist");
        L_Playlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_PlaylistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L_PlaylistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L_PlaylistMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_PlaylistLayout = new javax.swing.GroupLayout(pn_Playlist);
        pn_Playlist.setLayout(pn_PlaylistLayout);
        pn_PlaylistLayout.setHorizontalGroup(
            pn_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_PlaylistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_Playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pn_PlaylistLayout.setVerticalGroup(
            pn_PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_PlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Playlist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ikon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 28, Short.MAX_VALUE))
            .addComponent(pn_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_Artist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_Playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ikon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(pn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_Artist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_Playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_atas.add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(19, 19, 44));

        ps_utama.setBorder(null);
        ps_utama.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pn_utama.setBackground(new java.awt.Color(19, 19, 44));
        pn_utama.setLayout(new java.awt.BorderLayout());
        ps_utama.setViewportView(pn_utama);

        javax.swing.GroupLayout pn_kananLayout = new javax.swing.GroupLayout(pn_kanan);
        pn_kanan.setLayout(pn_kananLayout);
        pn_kananLayout.setHorizontalGroup(
            pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ps_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_kananLayout.setVerticalGroup(
            pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ps_utama)
                .addContainerGap())
        );

        pn_atas.add(pn_kanan, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_atas, java.awt.BorderLayout.CENTER);

        pn_bawah.setBackground(new java.awt.Color(255, 255, 255));
        pn_bawah.setForeground(new java.awt.Color(255, 255, 255));
        pn_bawah.setPreferredSize(new java.awt.Dimension(1260, 45));

        javax.swing.GroupLayout pn_bawahLayout = new javax.swing.GroupLayout(pn_bawah);
        pn_bawah.setLayout(pn_bawahLayout);
        pn_bawahLayout.setHorizontalGroup(
            pn_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1394, Short.MAX_VALUE)
        );
        pn_bawahLayout.setVerticalGroup(
            pn_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(pn_bawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_HomeMouseClicked
        L_Home.setForeground(new Color(44,25,55));

        pn_utama.removeAll();
        pn_utama.add(new Home());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_L_HomeMouseClicked

    private void L_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_HomeMouseEntered
        L_Home.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_L_HomeMouseEntered

    private void L_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_HomeMouseExited
        L_Home.setForeground(new Color(144,144,144));
    }//GEN-LAST:event_L_HomeMouseExited

    private void L_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_SearchMouseClicked
        L_Search.setForeground(new Color(44,25,55));

        pn_utama.removeAll();
        pn_utama.add(new Search());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_L_SearchMouseClicked

    private void L_SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_SearchMouseEntered
        L_Search.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_L_SearchMouseEntered

    private void L_SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_SearchMouseExited
        L_Search.setForeground(new Color(144,144,144));
    }//GEN-LAST:event_L_SearchMouseExited

    private void L_ArtistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ArtistMouseExited
        L_Artist.setForeground(new Color(144,144,144));
    }//GEN-LAST:event_L_ArtistMouseExited

    private void L_ArtistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ArtistMouseEntered
        L_Artist.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_L_ArtistMouseEntered

    private void L_ArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ArtistMouseClicked
        L_Artist.setForeground(new Color(44,25,55));

        pn_utama.removeAll();
        pn_utama.add(new Artist());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_L_ArtistMouseClicked

    private void L_PlaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_PlaylistMouseClicked
        L_Playlist.setForeground(new Color(44,25,55));

        pn_utama.removeAll();
        pn_utama.add(new Playlist());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_L_PlaylistMouseClicked

    private void L_PlaylistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_PlaylistMouseEntered
        L_Playlist.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_L_PlaylistMouseEntered

    private void L_PlaylistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_PlaylistMouseExited
        L_Playlist.setForeground(new Color(144,144,144));
    }//GEN-LAST:event_L_PlaylistMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Artist;
    private javax.swing.JLabel L_Home;
    private javax.swing.JLabel L_Playlist;
    private javax.swing.JLabel L_Search;
    private javax.swing.JLabel ikon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pn_Artist;
    private javax.swing.JPanel pn_Home;
    private javax.swing.JPanel pn_Playlist;
    private javax.swing.JPanel pn_Search;
    private javax.swing.JPanel pn_atas;
    private javax.swing.JPanel pn_bawah;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JScrollPane ps_utama;
    // End of variables declaration//GEN-END:variables
}
