/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_utama;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author asus
 */
public class AddPlaylist extends javax.swing.JPanel {

    /**
     * Creates new form AddPlaylist
     */
    JPanel pn;
    
    
    public AddPlaylist( JPanel pn) {
        initComponents();
        this.pn = pn;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        lb_playlistlogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_nameofPlaylist = new javax.swing.JLabel();
        bt_save = new rojerusan.RSMaterialButtonRectangle();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(19, 19, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(22, 27, 61));
        jTextField1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 480, 40));

        lb_playlistlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/playlist(small).png"))); // NOI18N
        jPanel1.add(lb_playlistlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 844, 338));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Rectangle 2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        lb_nameofPlaylist.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lb_nameofPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        lb_nameofPlaylist.setText("Name of Playlist");
        jPanel1.add(lb_nameofPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        bt_save.setBackground(new java.awt.Color(22, 27, 61));
        bt_save.setBorder(null);
        bt_save.setText("SAVE");
        bt_save.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });
        jPanel1.add(bt_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        JOptionPane.showMessageDialog(null, "Playlist created");
        
       pn.removeAll();
       pn.add(new Download1(pn));
       pn.repaint();
       pn.revalidate();
    }//GEN-LAST:event_bt_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle bt_save;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_nameofPlaylist;
    private javax.swing.JLabel lb_playlistlogo;
    // End of variables declaration//GEN-END:variables
}
