/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_utama;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Model_Playlist;

/**
 *
 * @author asus
 */
public class ChooseMusic extends javax.swing.JPanel {

   public JPanel pn;
   public Model_Playlist playlist;
    private DefaultListModel<String> listModel;
    public ChooseMusic(JPanel panel, Model_Playlist data) {
        initComponents();
        this.pn = panel;
        this.playlist = data;
        listModel = new DefaultListModel<>();
        
        //Karena ini tidak berkaitan dengan MP3 (pemutaran lagu) jadi cuma nampilin judulnya aja
        //menampilkan lagu yang sudah di download.
        listModel.addElement("Mary on a.mp3");//judul lagunya
        listModel.addElement("Cupid");
        listModel.addElement("apa");
        
        MusicListforChoose.setModel(listModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MusicListforChoose = new javax.swing.JList<>();

        setBackground(new java.awt.Color(19, 19, 44));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(19, 19, 44));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose a song");

        MusicListforChoose.setBackground(new java.awt.Color(19, 19, 44));
        MusicListforChoose.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        MusicListforChoose.setForeground(new java.awt.Color(255, 255, 255));
        MusicListforChoose.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        MusicListforChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicListforChooseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MusicListforChoose);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(560, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void MusicListforChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicListforChooseMouseClicked
        int selectedIndex = MusicListforChoose.getSelectedIndex();
        
       JOptionPane.showMessageDialog(null, "songs have been added to "+ playlist.getTitle());
        
       pn.removeAll();
       pn.add(new FillPlaylist(playlist, pn));
       pn.repaint();
       pn.revalidate();
    }//GEN-LAST:event_MusicListforChooseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> MusicListforChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
