/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_utama;

import Database.Database;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Model_Music;
import model.Model_Playlist;
import Database.Database;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author asus
 */
public class ChooseMusic extends javax.swing.JPanel {

   public JPanel pn;
   public Model_Playlist playlist;
   private DefaultListModel<String> listModel;
   private DefaultListModel<Model_Music> listMusic;
   Database db = new Database();
   Model_Music ms;
    public ChooseMusic(JPanel panel, Model_Playlist data) throws ClassNotFoundException, SQLException {
        initComponents();
        this.pn = panel;
        this.playlist = data;
        listModel = new DefaultListModel<>();
        listMusic = new DefaultListModel<>();
        
        ResultSet rs = db.getUserMusic(Database.getIDAccUser());
        while(rs.next()){
            listModel.addElement(rs.getString("name"));
            ms = new Model_Music();
            ms.setName(rs.getString("name"));
            ms.setNo(rs.getInt("songID"));
            listMusic.addElement(ms);
        }
        
        MusicListforChoose.setModel(listModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MusicListforChoose = new javax.swing.JList<>();

        setBackground(new java.awt.Color(19, 19, 44));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(19, 19, 44));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose a song");

        MusicListforChoose.setBackground(new java.awt.Color(19, 19, 44));
        MusicListforChoose.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        MusicListforChoose.setForeground(new java.awt.Color(255, 255, 255));
        MusicListforChoose.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        MusicListforChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicListforChooseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(MusicListforChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(MusicListforChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void MusicListforChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicListforChooseMouseClicked
       try {
           int selectedIndex = MusicListforChoose.getSelectedIndex();
           String sql = "SongID = " + listMusic.getElementAt(selectedIndex).getNo() + " && PlaylistID = " + playlist.getID();
           ResultSet rs = db.getDBWhere("playlistsong", sql);
           
            if(rs.next()){
                   JOptionPane.showMessageDialog(null, "lagu sudah ada");
               } else {
                   if(db.insertMusicToPlaylist(playlist.getID(), listMusic.getElementAt(selectedIndex).getNo())){
                    JOptionPane.showMessageDialog(null, "songs have been added to "+ playlist.getTitle());

                     pn.removeAll();
                     pn.add(new FillPlaylist(playlist, pn));
                     pn.repaint();
                     pn.revalidate();
                } else {
                    JOptionPane.showMessageDialog(null, "Unexpected Error");
                }
               }
           
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(ChooseMusic.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(ChooseMusic.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_MusicListforChooseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> MusicListforChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
