/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_utama;

import component.bottomMenu;
import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JPanel;
import model.Model_Music;
import model.Model_Playlist;
import model.Model_User;

/**
 *
 * @author asus
 */
public class Download1 extends javax.swing.JPanel {

    /**
     * Creates new form Download
     */
    JPanel pn;
    
    MP3Player player = new MP3Player();
    private DefaultListModel<String> listModel;
    Model_User user = new Model_User(player);
    int j = 0;
    
    public Download1(JPanel pn) {
        
        listModel = new DefaultListModel<>();
        this.pn = pn;
        initComponents();
       
        //Menampilkan daftar Playlist
       mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
       mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
       mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
       mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
       mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
        
        // Tambahkan lagu ke playlist dan JList
        //jika sudah ada databasenya mungkin parameternya dari value kolom-kolom di databasenya
        user.addMusik(new Model_Music("1", "Ammakku Surugaku", "03:00", "D:\\Ammaku.mp3"));
        listModel.addElement("Ammakku Surugaku");//judul lagunya
        user.addMusik(new Model_Music("2", "Duriat Pegat", "03:00", "D:\\DuriatPegat.mp3"));
        listModel.addElement("Duriat Pegat");
        user.addMusik(new Model_Music("2", "Inget Ka Mantan", "03:00", "D:\\IngetKaMantan.mp3"));
        listModel.addElement("Inget Ka Mantan");
        user.addMusik(new Model_Music("2", "Keloas", "03:00", "D:\\Keloas.mp3"));
        listModel.addElement("Keloas");
        user.addMusik(new Model_Music("2", "Rek Ayo Rek", "03:00", "D:\\rekAyorek.mp3"));
        listModel.addElement("Rek Ayo Rek");
        user.addMusik(new Model_Music("2", "Segara Madu", "03:00", "D:\\SegaraMadu.mp3"));
        listModel.addElement("Segara Madu");
        
        
   
        
        //memasukkan listmodel ke playlistlagu (JList)
        playlistLagu.setModel(listModel);
        
        

        
        
        
        
    }
    
   

    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_addPlaylist = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_playlist = new javax.swing.JLabel();
        mostPopular1 = new component.MostPopular();
        jPanel2 = new javax.swing.JPanel();
        bt_play = new javax.swing.JLabel();
        bt_pause = new javax.swing.JLabel();
        bt_stop = new javax.swing.JLabel();
        bt_backward = new javax.swing.JLabel();
        bt_forward = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playlistLagu = new javax.swing.JList<>();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(19, 19, 44));

        bt_addPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/plus_1.png"))); // NOI18N
        bt_addPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addPlaylistMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Download");

        lb_playlist.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lb_playlist.setForeground(new java.awt.Color(255, 255, 255));
        lb_playlist.setText("Playlist");

        jPanel2.setBackground(new java.awt.Color(4, 1, 32));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/play.png"))); // NOI18N
        bt_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_playMouseClicked(evt);
            }
        });
        jPanel2.add(bt_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        bt_pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pause.png"))); // NOI18N
        bt_pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_pauseMouseClicked(evt);
            }
        });
        jPanel2.add(bt_pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        bt_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/stop.png"))); // NOI18N
        bt_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_stopMouseClicked(evt);
            }
        });
        jPanel2.add(bt_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        bt_backward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/forward.png"))); // NOI18N
        bt_backward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_backwardMouseClicked(evt);
            }
        });
        jPanel2.add(bt_backward, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        bt_forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/backward.png"))); // NOI18N
        bt_forward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_forwardMouseClicked(evt);
            }
        });
        jPanel2.add(bt_forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        playlistLagu.setBackground(new java.awt.Color(19, 19, 44));
        playlistLagu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        playlistLagu.setForeground(new java.awt.Color(255, 255, 255));
        playlistLagu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(playlistLagu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lb_playlist))
                        .addGap(865, 865, 865)
                        .addComponent(bt_addPlaylist)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(mostPopular1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_playlist))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(bt_addPlaylist)))
                .addGap(10, 10, 10)
                .addComponent(mostPopular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addPlaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addPlaylistMouseClicked
       pn.removeAll();
       pn.add(new AddPlaylist(pn));
       pn.repaint();
       pn.revalidate();
    }//GEN-LAST:event_bt_addPlaylistMouseClicked

    private void bt_playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_playMouseClicked
        int selectedIndex = playlistLagu.getSelectedIndex();
                
                if (selectedIndex != -1) {
                    if(selectedIndex > j){
                        playSelectedSongForward(selectedIndex);
                    }else if(selectedIndex < j){
                        playSelectedSongBackward( selectedIndex);
                    }else{
                        user.play();
                    }
                }
    }//GEN-LAST:event_bt_playMouseClicked

    private void bt_pauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pauseMouseClicked
        user.pause();
    }//GEN-LAST:event_bt_pauseMouseClicked

    private void bt_stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_stopMouseClicked
        user.stop();
    }//GEN-LAST:event_bt_stopMouseClicked

    private void bt_backwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backwardMouseClicked
        user.skipBackward();
       
            j--;
            playlistLagu.setSelectedIndex(j);
        
        
        
    }//GEN-LAST:event_bt_backwardMouseClicked

    private void bt_forwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_forwardMouseClicked
        user.skipForward();
       
            j++;
            playlistLagu.setSelectedIndex(j);
            
    }//GEN-LAST:event_bt_forwardMouseClicked

        private void playSelectedSongForward(int selectedIndex) {
         // Dapatkan indeks lagu yang akan diputar
        int index = selectedIndex;

        // Atur pemutaran lagu sesuai indeks
        if (index != -1) {
            // Hentikan pemutaran yang sedang berlangsung
            user.stop();
            
            for (int i = j; i < index; i++) {
                 // Skip ke lagu yang dipilih
                user.skipForward();
                    
            }
                
            
            // Mulai pemutaran
            user.play();
            j = index;
            
        }
    }
    
    private void playSelectedSongBackward(int selectedIndex) {
        // Dapatkan indeks lagu yang akan diputar
        int index = selectedIndex;

        // Atur pemutaran lagu sesuai indeks
        if (index != -1) {
            // Hentikan pemutaran yang sedang berlangsung
            user.stop();
            int i = j;
            // Skip ke lagu yang dipilih
            while(i > index){
                user.skipBackward();
                i--;
                
            }
            

            // Mulai pemutaran
            user.play();
            j = index;
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_addPlaylist;
    private javax.swing.JLabel bt_backward;
    private javax.swing.JLabel bt_forward;
    private javax.swing.JLabel bt_pause;
    private javax.swing.JLabel bt_play;
    private javax.swing.JLabel bt_stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_playlist;
    private component.MostPopular mostPopular1;
    private javax.swing.JList<String> playlistLagu;
    // End of variables declaration//GEN-END:variables

    
}
