/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_utama;

import jaco.mp3.player.MP3Player;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import model.Model_Music;
import model.Model_Playlist;
import model.Model_User;


public class FillPlaylist extends javax.swing.JPanel {

    
    JPanel panel;
    Model_Playlist data;
    MP3Player player = new MP3Player();
    private DefaultListModel<String> listModel;
    Model_User user = new Model_User(player);
    int j = 0;
    
    
    public FillPlaylist( Model_Playlist data, JPanel pn) {
        listModel = new DefaultListModel<>();
        initComponents();
        this.panel = pn;
        this.data = data;
        L_playlistName.setText(data.getTitle().trim());
        
        // Tambahkan lagu ke playlist dan JList
        //jika sudah ada databasenya mungkin parameternya dari value kolom-kolom di databasenya
        user.addMusik(new Model_Music("1", "Mary on a", "03:00", "D:\\lagu1.mp3"));
        listModel.addElement("Mary on a.mp3");//judul lagunya
        user.addMusik(new Model_Music("2", "cupid", "03:00", "D:\\lagu2.mp3"));
        listModel.addElement("Cupid");
        
        
        
   
        
        //memasukkan listmodel ke playlistlagu (JList)
        MusicPlaylist.setModel(listModel);
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFill = new javax.swing.JPanel();
        L_playlistName = new javax.swing.JLabel();
        bt_addsong = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt_play = new javax.swing.JLabel();
        bt_pause = new javax.swing.JLabel();
        bt_stop = new javax.swing.JLabel();
        bt_backward = new javax.swing.JLabel();
        bt_forward = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MusicPlaylist = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(1110, 620));
        setLayout(new java.awt.CardLayout());

        pnFill.setBackground(new java.awt.Color(19, 19, 44));

        L_playlistName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        L_playlistName.setForeground(new java.awt.Color(255, 255, 255));
        L_playlistName.setText("YOUR PLAYLIST");

        bt_addsong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/plus_1.png"))); // NOI18N
        bt_addsong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addsongMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(4, 1, 32));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/play.png"))); // NOI18N
        bt_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_playMouseClicked(evt);
            }
        });
        jPanel2.add(bt_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        bt_pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pause.png"))); // NOI18N
        bt_pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_pauseMouseClicked(evt);
            }
        });
        jPanel2.add(bt_pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        bt_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/stop.png"))); // NOI18N
        bt_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_stopMouseClicked(evt);
            }
        });
        jPanel2.add(bt_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        bt_backward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/forward.png"))); // NOI18N
        bt_backward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_backwardMouseClicked(evt);
            }
        });
        jPanel2.add(bt_backward, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        bt_forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/backward.png"))); // NOI18N
        bt_forward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_forwardMouseClicked(evt);
            }
        });
        jPanel2.add(bt_forward, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        MusicPlaylist.setBackground(new java.awt.Color(19, 19, 44));
        MusicPlaylist.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        MusicPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        MusicPlaylist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(MusicPlaylist);

        javax.swing.GroupLayout pnFillLayout = new javax.swing.GroupLayout(pnFill);
        pnFill.setLayout(pnFillLayout);
        pnFillLayout.setHorizontalGroup(
            pnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFillLayout.createSequentialGroup()
                .addGroup(pnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnFillLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(L_playlistName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_addsong)
                        .addGap(13, 13, 13)))
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
        );
        pnFillLayout.setVerticalGroup(
            pnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_playlistName)
                    .addComponent(bt_addsong))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );

        add(pnFill, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addsongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addsongMouseClicked
       panel.removeAll();
       panel.add(new ChooseMusic(panel, data));
       panel.repaint();
       panel.revalidate();
    }//GEN-LAST:event_bt_addsongMouseClicked

    private void bt_playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_playMouseClicked
        int selectedIndex = MusicPlaylist.getSelectedIndex();

        if (selectedIndex != -1) {
            String selectedSong = listModel.getElementAt(selectedIndex);
            if(selectedIndex > j){
                playSelectedSongForward(selectedSong);
            }else if(selectedIndex < j){
                playSelectedSongBackward(selectedSong);
            }else{
                user.play();
            }
        }
    }//GEN-LAST:event_bt_playMouseClicked

    private void bt_pauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pauseMouseClicked
        user.pause();
    }//GEN-LAST:event_bt_pauseMouseClicked

    private void bt_stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_stopMouseClicked
        user.stop();
    }//GEN-LAST:event_bt_stopMouseClicked

    private void bt_backwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backwardMouseClicked
        user.skipBackward();
        j--;
        MusicPlaylist.setSelectedIndex(j);
    }//GEN-LAST:event_bt_backwardMouseClicked

    private void bt_forwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_forwardMouseClicked
        user.skipForward();
        j++;
        MusicPlaylist.setSelectedIndex(j);
    }//GEN-LAST:event_bt_forwardMouseClicked
        private void playSelectedSongForward(String song) {
        // Dapatkan indeks lagu yang akan diputar
        int index = listModel.indexOf(song);

        // Atur pemutaran lagu sesuai indeks
        if (index != -1) {
            // Hentikan pemutaran yang sedang berlangsung
            user.stop();

            // Skip ke lagu yang dipilih
            for (int i = j; i < index; i++) {
                user.skipForward();
            }
            

            // Mulai pemutaran
            user.play();
            j = index;
        }
    }
    
    private void playSelectedSongBackward(String song) {
        // Dapatkan indeks lagu yang akan diputar
        int index = listModel.indexOf(song);

        // Atur pemutaran lagu sesuai indeks
        if (index != -1) {
            // Hentikan pemutaran yang sedang berlangsung
            player.stop();
            int i = j;
            // Skip ke lagu yang dipilih
            while(i != index){
                player.skipBackward();
                i--;
                
            }
            

            // Mulai pemutaran
            player.play();
            j = index;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_playlistName;
    private javax.swing.JList<String> MusicPlaylist;
    private javax.swing.JLabel bt_addsong;
    private javax.swing.JLabel bt_backward;
    private javax.swing.JLabel bt_forward;
    private javax.swing.JLabel bt_pause;
    private javax.swing.JLabel bt_play;
    private javax.swing.JLabel bt_stop;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnFill;
    // End of variables declaration//GEN-END:variables
}
