
package Menu_utama;


import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Model_Artist;
import model.Model_Music;

import projek_latih2.admin;


public class Home extends javax.swing.JPanel {

   
    //pn itu buat merubah tampilan pn_utama di NewJframe supaya pn_utama berganti.
    private JPanel pn;
    private DefaultListModel<String> listModel;
    
    public Home(JPanel pn) {
        initComponents();
        this.pn = pn;
        listModel = new DefaultListModel<>();
        init();
        
        //Karena ini tidak berkaitan dengan MP3 (pemutaran lagu) jadi cuma nampilin judulnya aja
        listModel.addElement("Mary on a");//judul lagunya
        listModel.addElement("Cupid");
        
        
        MusicList.setModel(listModel);
      
        
       
    }
    public Home(){
        
    }
    private void init() {
       
        //Menampilkan artis (paling nanti yang diganti cuma nama artisnya aja, kalo deskripsi mungkin nanti bisa dihapus)
       mostArtist1.addImage(new Model_Artist(new ImageIcon(getClass().getResource("/gambar/Artist.png")), "Anggun", "15 Albums | 17.5M Follower"), pn);
       mostArtist1.addImage(new Model_Artist(new ImageIcon(getClass().getResource("/gambar/Artist.png")), "Nike Ardilla", "15 Albums | 17.5M Follower"), pn);
       mostArtist1.addImage(new Model_Artist(new ImageIcon(getClass().getResource("/gambar/Artist.png")), "Inka Christie", "15 Albums | 17.5M Follower"), pn);
       mostArtist1.addImage(new Model_Artist(new ImageIcon(getClass().getResource("/gambar/Artist.png")), "Nicky Astria", "15 Albums | 17.5M Follower"), pn);
       mostArtist1.addImage(new Model_Artist(new ImageIcon(getClass().getResource("/gambar/Artist.png")), "Melly Goeslaw", "15 Albums | 17.5M Follower"), pn);
       mostArtist1.addImage(new Model_Artist(new ImageIcon(getClass().getResource("/gambar/Artist.png")), "Poppy Mercury", "15 Albums | 17.5M Follower"), pn);
       
      
       
        
        
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mostArtist1 = new component.MostArtist();
        jScrollPane1 = new javax.swing.JScrollPane();
        MusicList = new javax.swing.JList<>();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(19, 19, 44));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel2.setText("Track");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Home");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Artist");

        MusicList.setBackground(new java.awt.Color(19, 19, 44));
        MusicList.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        MusicList.setForeground(new java.awt.Color(255, 255, 255));
        MusicList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        MusicList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MusicList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mostArtist1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostArtist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE))
        );

        add(jPanel1, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void MusicListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicListMouseClicked
        int selectedIndex = MusicList.getSelectedIndex();
        
        //mekanisme memindahkan lagu ke download berdasarkan judul lagu yang sudah dipilih
        
        
        //ketika berhasil
        JOptionPane.showMessageDialog(null, "song successfully downloaded");;
    }//GEN-LAST:event_MusicListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> MusicList;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private component.MostArtist mostArtist1;
    // End of variables declaration//GEN-END:variables
}
