
package Menu_utama;


import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Model_Artist;
import model.Model_Music;
import Database.Database;
import com.mysql.cj.protocol.Resultset;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import projek_latih2.admin;


public class Home extends javax.swing.JPanel {

   
    //pn itu buat merubah tampilan pn_utama di NewJframe supaya pn_utama berganti.
    private JPanel pn;
    private DefaultListModel<String> listModel;
    private DefaultListModel<Model_Music> listMusic;
    Database db = new Database();
    boolean check;
    Model_Music ms;
    
    public Home(JPanel pn) throws SQLException {
        initComponents();
        this.pn = pn;
        listModel = new DefaultListModel<>();
        listMusic = new DefaultListModel<>();
        check = false;

        ResultSet rs = db.getDB("song");
        while(rs.next()){
            listModel.addElement(rs.getString("name"));
            ms = new Model_Music();
            ms.setName(rs.getString("name"));
            ms.setPenyanyi(rs.getString("artist"));
            ms.setNo(rs.getInt("songID"));
            ms.setLink(rs.getString("Link_Lagu"));
            listMusic.addElement(ms);
        }
        
        init();
        
        //Karena ini tidak berkaitan dengan MP3 (pemutaran lagu) jadi cuma nampilin judulnya aja
        //judul lagunya
        
        
        
        
        MusicList.setModel(listModel);
      
        
       
    }
    public Home(){
        
    }
    private void init() {
       
        //Menampilkan artis (paling nanti yang diganti cuma nama artisnya aja, kalo deskripsi mungkin nanti bisa dihapus)
       int i = 0;
       while(i < listMusic.size()){
           mostArtist1.addImage(new Model_Artist(new ImageIcon(getClass().getResource("/gambar/Artist.png")), listMusic.getElementAt(i).getPenyanyi(), ""), pn);
           i++;
       }
       
       
      
       
        
        
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mostArtist1 = new component.MostArtist();
        MusicList = new javax.swing.JList<>();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(19, 19, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Music Tracks");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Home");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Artist");

        MusicList.setBackground(new java.awt.Color(19, 19, 44));
        MusicList.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        MusicList.setForeground(new java.awt.Color(255, 255, 255));
        MusicList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        MusicList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostArtist1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(MusicList, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(502, 502, 502))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostArtist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(MusicList, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void MusicListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicListMouseClicked
        try {
            check = false;
            int selectedIndex = MusicList.getSelectedIndex();
            
            //mekanisme memindahkan lagu ke download berdasarkan judul lagu yang sudah dipilih
            ResultSet rs = db.getDB("usersong");
            while(rs.next()){
                if(rs.getInt("userID") == Database.getIDAccUser()){
                    if(rs.getInt("SongID") == listMusic.getElementAt(selectedIndex).getNo()){
                        check = true;
                    }
                }
            }
            if (!check){
                String Dir = db.Download(listMusic.getElementAt(selectedIndex).getLink(), listMusic.getElementAt(selectedIndex).getName());
                db.insertMusicToUser(Database.getIDAccUser(), listMusic.getElementAt(selectedIndex).getNo(), Dir);
                listMusic.getElementAt(selectedIndex).setDirectory("./src/Music/" + listMusic.getElementAt(selectedIndex).getName() + ".mp3");
                JOptionPane.showMessageDialog(null, "song successfully downloaded");
            } else{
                JOptionPane.showMessageDialog(null, "song already added");;
            }
            
            
            //ketika berhasil
            
        } catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_MusicListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> MusicList;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private component.MostArtist mostArtist1;
    // End of variables declaration//GEN-END:variables
}
