/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_utama;
import java.awt.Color;
import javax.swing.JFrame;
import projek_latih2.login;
import Method.*;
import java.util.Random;
import Database.Database;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author asus
 */
public class RegisPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisPanel
     */
    private JFrame frame;
    Database db = new Database();
    Random rd = new Random();
    public RegisPanel(JFrame frame) {
        this.frame = frame;
        initComponents();
      
        setOpaque(false);
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        custom1 = new palette.PanelCustom();
        tx_username = new javax.swing.JTextField();
        tx_pass = new javax.swing.JTextField();
        lb_labelbiasa = new javax.swing.JLabel();
        bt_regis = new rojerusan.RSMaterialButtonRectangle();
        lb_FieldUsername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.CardLayout());

        custom1.setBackground(new java.awt.Color(1, 4, 32));
        custom1.setRoundBottomLeft(20);
        custom1.setRoundBottomRight(20);
        custom1.setRoundTopLeft(20);
        custom1.setRoundTopright(20);
        custom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tx_username.setBackground(new java.awt.Color(217, 217, 217));
        tx_username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        tx_username.setText("Username");
        tx_username.setBorder(null);
        tx_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tx_usernameFocusLost(evt);
            }
        });
        custom1.add(tx_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 240, 30));

        tx_pass.setBackground(new java.awt.Color(217, 217, 217));
        tx_pass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        tx_pass.setText("Password");
        tx_pass.setBorder(null);
        tx_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tx_passFocusLost(evt);
            }
        });
        custom1.add(tx_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 240, 30));

        lb_labelbiasa.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lb_labelbiasa.setForeground(new java.awt.Color(255, 255, 255));
        lb_labelbiasa.setText("Please register");
        custom1.add(lb_labelbiasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        bt_regis.setBackground(new java.awt.Color(217, 217, 217));
        bt_regis.setBorder(null);
        bt_regis.setForeground(new java.awt.Color(0, 0, 0));
        bt_regis.setText("register");
        bt_regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_regisActionPerformed(evt);
            }
        });
        custom1.add(bt_regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, 50));

        lb_FieldUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/textFieldicon.png"))); // NOI18N
        custom1.add(lb_FieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/textFieldicon.png"))); // NOI18N
        custom1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Cancel_3.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        custom1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jPanel1.add(custom1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_regisActionPerformed
        try {
            Database.setIDAccUser(rd.nextInt(10000));
            if (db.insertRegDB(tx_username.getText(), tx_pass.getText(), Database.getIDAccUser())){
                jPanel1.removeAll();
                jPanel1.add(new LoginPanel(frame));
                jPanel1.repaint();
                jPanel1.revalidate();
            }else {
                JOption msg = new JOption();
                msg.warning(this, "Sorry, username already taken");
            }
            
            /*
            Dipake ketika username already taken
            JOption msg = new JOption();
            msg.warning(this, "Sorry, username already taken");
            */
        } catch (SQLException ex) {
            Logger.getLogger(RegisPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_regisActionPerformed

    private void tx_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_usernameFocusGained
        String username = tx_username.getText();
        if(username.equals("Username")){
            tx_username.setText("");
        }
    }//GEN-LAST:event_tx_usernameFocusGained

    private void tx_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_usernameFocusLost
        String username=tx_username.getText();
        if(username.equals("") || username.equals("Username")){
            tx_username.setText("Username");
        }
    }//GEN-LAST:event_tx_usernameFocusLost

    private void tx_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_passFocusGained
        String pass = tx_pass.getText();
        if(pass.equals("Password")){
            tx_pass.setText("");
        }
    }//GEN-LAST:event_tx_passFocusGained

    private void tx_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_passFocusLost
        String pass=tx_pass.getText();
        if(pass.equals("") || pass.equals("Password")){
            tx_pass.setText("Password");
        }
    }//GEN-LAST:event_tx_passFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        frame.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle bt_regis;
    private palette.PanelCustom custom1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_FieldUsername;
    private javax.swing.JLabel lb_labelbiasa;
    private javax.swing.JTextField tx_pass;
    private javax.swing.JTextField tx_username;
    // End of variables declaration//GEN-END:variables
}
