/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_utama;

import component.bottomMenu;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import model.Model_Music;
import model.Model_Playlist;

/**
 *
 * @author asus
 */
public class Download extends javax.swing.JPanel {

    /**
     * Creates new form Download
     */
    JPanel pn;
    bottomMenu bottomMenu;
    public Download(bottomMenu panel, JPanel pn) {
        initComponents();
        musicDownload1.init(panel);
        mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
        mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
        mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
        mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
        mostPopular1.addImage(new Model_Playlist(new ImageIcon(getClass().getResource("/gambar/Playlist.png")), "Lagu kesukaan"), pn);
        this.pn = pn;
        this.bottomMenu = panel;
        
    }
    
   

    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_addPlaylist = new javax.swing.JLabel();
        musicDownload1 = new component.MusicDownload();
        jLabel1 = new javax.swing.JLabel();
        lb_playlist = new javax.swing.JLabel();
        mostPopular1 = new component.MostPopular();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(19, 19, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_addPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/plus_1.png"))); // NOI18N
        bt_addPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addPlaylistMouseClicked(evt);
            }
        });
        jPanel1.add(bt_addPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, -1, -1));
        jPanel1.add(musicDownload1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 350, 1087, 257));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Download");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 21, -1, -1));

        lb_playlist.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lb_playlist.setForeground(new java.awt.Color(255, 255, 255));
        lb_playlist.setText("Playlist");
        jPanel1.add(lb_playlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 75, -1, -1));
        jPanel1.add(mostPopular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1087, -1));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addPlaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addPlaylistMouseClicked
       pn.removeAll();
       pn.add(new AddPlaylist(pn));
       pn.repaint();
       pn.revalidate();
    }//GEN-LAST:event_bt_addPlaylistMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_addPlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_playlist;
    private component.MostPopular mostPopular1;
    private component.MusicDownload musicDownload1;
    // End of variables declaration//GEN-END:variables

    
}
