/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_utama;

import model.Model_Popular;

/**
 *
 * @author asus
 */
public class FillPlaylist extends javax.swing.JPanel {

    /**
     * Creates new form FillPlaylist
     */
    public FillPlaylist(Model_Popular data) {
        initComponents();
        L_playlistName.setText(data.getTitle().trim());
        L_Description.setText(data.getDescription().trim());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFill = new javax.swing.JPanel();
        L_playlistName = new javax.swing.JLabel();
        L_Description = new javax.swing.JLabel();
        music1 = new component.Music();

        setLayout(new java.awt.CardLayout());

        pnFill.setBackground(new java.awt.Color(19, 19, 44));

        L_playlistName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        L_playlistName.setForeground(new java.awt.Color(255, 255, 255));
        L_playlistName.setText("YOUR PLAYLIST");

        L_Description.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        L_Description.setForeground(new java.awt.Color(255, 255, 255));
        L_Description.setText("Description");

        javax.swing.GroupLayout pnFillLayout = new javax.swing.GroupLayout(pnFill);
        pnFill.setLayout(pnFillLayout);
        pnFillLayout.setHorizontalGroup(
            pnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_playlistName)
                    .addComponent(L_Description))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnFillLayout.createSequentialGroup()
                .addComponent(music1, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        pnFillLayout.setVerticalGroup(
            pnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_playlistName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(music1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnFill, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Description;
    private javax.swing.JLabel L_playlistName;
    private component.Music music1;
    private javax.swing.JPanel pnFill;
    // End of variables declaration//GEN-END:variables
}
