
package projek_latih2;

import Menu_utama.Search;
import Menu_utama.Home;

import Menu_utama.Download1;
import java.awt.Color;
import Method.ScrollBar;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Model_Music;
/**
 *
 * @author Adrian Aditya P
 */

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Model_Music musicUser;
    public NewJFrame() throws SQLException {
        initComponents();
        init();
        //setBackground(new Color(0,0,0,0));
        L_Home.setForeground(new Color(44,25,55));

        pn_utama.removeAll();
        pn_utama.add(new Home(pn_utama));
        pn_utama.repaint();
        pn_utama.revalidate();
       
        
        
    }
   
    
    
    
    
    private void init(){
        ps_utama.setVerticalScrollBar(new ScrollBar());
    }
    
    
   
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_atas = new javax.swing.JPanel();
        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pn_Home = new javax.swing.JPanel();
        L_Home = new javax.swing.JLabel();
        pn_Search = new javax.swing.JPanel();
        L_Search = new javax.swing.JLabel();
        pn_download = new javax.swing.JPanel();
        L_Download = new javax.swing.JLabel();
        lb_ikon = new javax.swing.JLabel();
        pn_Exit = new javax.swing.JPanel();
        L_Exit = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        ps_utama = new javax.swing.JScrollPane();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_atas.setBackground(new java.awt.Color(19, 19, 44));
        pn_atas.setPreferredSize(new java.awt.Dimension(1260, 600));
        pn_atas.setLayout(new java.awt.BorderLayout());

        pn_kiri.setBackground(new java.awt.Color(4, 1, 32));
        pn_kiri.setPreferredSize(new java.awt.Dimension(150, 521));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Musikku");

        pn_Home.setBackground(new java.awt.Color(4, 1, 32));
        pn_Home.setForeground(new java.awt.Color(255, 255, 255));

        L_Home.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        L_Home.setForeground(new java.awt.Color(255, 255, 255));
        L_Home.setText("> Home");
        L_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L_HomeMouseExited(evt);
            }
        });

        pn_Search.setBackground(new java.awt.Color(4, 1, 32));

        L_Search.setBackground(new java.awt.Color(4, 1, 32));
        L_Search.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        L_Search.setForeground(new java.awt.Color(255, 255, 255));
        L_Search.setText("> Search");
        L_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L_SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L_SearchMouseExited(evt);
            }
        });

        pn_download.setBackground(new java.awt.Color(4, 1, 32));

        L_Download.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        L_Download.setForeground(new java.awt.Color(255, 255, 255));
        L_Download.setText("> Download");
        L_Download.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_DownloadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L_DownloadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L_DownloadMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_downloadLayout = new javax.swing.GroupLayout(pn_download);
        pn_download.setLayout(pn_downloadLayout);
        pn_downloadLayout.setHorizontalGroup(
            pn_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_downloadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Download, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_downloadLayout.setVerticalGroup(
            pn_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_downloadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Download)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_SearchLayout = new javax.swing.GroupLayout(pn_Search);
        pn_Search.setLayout(pn_SearchLayout);
        pn_SearchLayout.setHorizontalGroup(
            pn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pn_download, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_SearchLayout.setVerticalGroup(
            pn_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_Search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_download, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pn_HomeLayout = new javax.swing.GroupLayout(pn_Home);
        pn_Home.setLayout(pn_HomeLayout);
        pn_HomeLayout.setHorizontalGroup(
            pn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(pn_Search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_HomeLayout.setVerticalGroup(
            pn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lb_ikon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 35 (1).png"))); // NOI18N
        lb_ikon.setText("jLabel2");

        pn_Exit.setBackground(new java.awt.Color(4, 1, 32));
        pn_Exit.setForeground(new java.awt.Color(255, 255, 255));

        L_Exit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        L_Exit.setForeground(new java.awt.Color(255, 255, 255));
        L_Exit.setText("> Exit");
        L_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L_ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L_ExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_ExitLayout = new javax.swing.GroupLayout(pn_Exit);
        pn_Exit.setLayout(pn_ExitLayout);
        pn_ExitLayout.setHorizontalGroup(
            pn_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_ExitLayout.setVerticalGroup(
            pn_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ExitLayout.createSequentialGroup()
                .addComponent(L_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_kiriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_ikon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lb_ikon, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(pn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn_atas.add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(19, 19, 44));

        ps_utama.setBorder(null);
        ps_utama.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pn_utama.setBackground(new java.awt.Color(19, 19, 44));
        pn_utama.setLayout(new java.awt.BorderLayout());
        ps_utama.setViewportView(pn_utama);

        javax.swing.GroupLayout pn_kananLayout = new javax.swing.GroupLayout(pn_kanan);
        pn_kanan.setLayout(pn_kananLayout);
        pn_kananLayout.setHorizontalGroup(
            pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ps_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_kananLayout.setVerticalGroup(
            pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ps_utama)
                .addContainerGap())
        );

        pn_atas.add(pn_kanan, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_atas, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void L_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_HomeMouseClicked
        try {
            L_Home.setForeground(new Color(44,25,55));
            
            pn_utama.removeAll();
            pn_utama.add(new Home(pn_utama));
            pn_utama.repaint();
            pn_utama.revalidate();
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_L_HomeMouseClicked

    private void L_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_HomeMouseEntered
        L_Home.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_L_HomeMouseEntered

    private void L_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_HomeMouseExited
        L_Home.setForeground(new Color(144,144,144));
    }//GEN-LAST:event_L_HomeMouseExited

    private void L_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_SearchMouseClicked
        L_Search.setForeground(new Color(44,25,55));

        pn_utama.removeAll();
        pn_utama.add(new Search());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_L_SearchMouseClicked

    private void L_SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_SearchMouseEntered
        L_Search.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_L_SearchMouseEntered

    private void L_SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_SearchMouseExited
        L_Search.setForeground(new Color(144,144,144));
    }//GEN-LAST:event_L_SearchMouseExited

    private void L_DownloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_DownloadMouseClicked
        try {
            L_Download.setForeground(new Color(44,25,55));
            
            pn_utama.removeAll();
            pn_utama.add(new Download1(pn_utama));
            pn_utama.repaint();
            pn_utama.revalidate();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_L_DownloadMouseClicked

    private void L_DownloadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_DownloadMouseEntered
       L_Download.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_L_DownloadMouseEntered

    private void L_DownloadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_DownloadMouseExited
        L_Download.setForeground(new Color(144,144,144));
    }//GEN-LAST:event_L_DownloadMouseExited

    private void L_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_L_ExitMouseClicked

    private void L_ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ExitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_L_ExitMouseEntered

    private void L_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_ExitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_L_ExitMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewJFrame().setVisible(true);
//            }
//        });
//    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Download;
    private javax.swing.JLabel L_Exit;
    private javax.swing.JLabel L_Home;
    private javax.swing.JLabel L_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_ikon;
    private javax.swing.JPanel pn_Exit;
    private javax.swing.JPanel pn_Home;
    private javax.swing.JPanel pn_Search;
    private javax.swing.JPanel pn_atas;
    private javax.swing.JPanel pn_download;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JScrollPane ps_utama;
    // End of variables declaration//GEN-END:variables
}
