/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_utama;

import model.Model_Artist;


/**
 *
 * @author asus
 */
public class FillArtist extends javax.swing.JPanel {

    /**
     * Creates new form FillPlaylist
     * @param data
     */
    public FillArtist(Model_Artist data) {
        initComponents();
        L_playlistName.setText(data.getTitle().trim());
        L_Description.setText(data.getDescription().trim());
        //perulangan buat ngambil lagu dari tabel 
        musicSearch1.init("1", "lagu ini", "03:00","Directory");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFill = new javax.swing.JPanel();
        L_playlistName = new javax.swing.JLabel();
        L_Description = new javax.swing.JLabel();
        musicSearch1 = new component.MusicSearch();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        pnFill.setBackground(new java.awt.Color(19, 19, 44));
        pnFill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_playlistName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        L_playlistName.setForeground(new java.awt.Color(255, 255, 255));
        L_playlistName.setText("ARTIST NAME");
        pnFill.add(L_playlistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        L_Description.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        L_Description.setForeground(new java.awt.Color(255, 255, 255));
        L_Description.setText("Description");
        pnFill.add(L_Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));
        pnFill.add(musicSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 1075, 359));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Artisti(playlist).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        pnFill.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, 0, 710, 260));

        add(pnFill, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Description;
    private javax.swing.JLabel L_playlistName;
    private javax.swing.JLabel jLabel1;
    private component.MusicSearch musicSearch1;
    private javax.swing.JPanel pnFill;
    // End of variables declaration//GEN-END:variables
}
